# Tensor
- ```Tensor``` : ```데이터를 표현하는 단위```

<img src='./Tensor 이미지.PNG' height=300px, width=600px>

# Scalar
- ```Scalar``` : ```하나의 값을 표현할 때 1개의 수치로 표현한 것```

In [3]:
import torch

scalar1 = torch.tensor([1.])
print(scalar1)
# tensor([1.])

scalar2 = torch.tensor([3.])
print(scalar2)
# tensor([3.])

tensor([1.])
tensor([3.])


- Scalar 사칙연산

    - 덧셈

In [6]:
add_scalar = scalar1 + scalar2
print(add_scalar)
# tensor([4.])

tensor([4.])


    - 뺄셈

In [7]:
sub_scalar = scalar1 - scalar2
print(sub_scalar)
# tensor([-2.])

tensor([-2.])


    - 곱셈

In [8]:
mul_scalar = scalar1 * scalar2
print(mul_scalar)
# tensor([3.])

tensor([3.])


    - 나눗셈

In [10]:
div_scalar = scalar1 / scalar2
print(div_scalar)
# tensor([0.3333])

tensor([0.3333])


# Vector
- ```Vector``` : ```하나의 값을 표현할 때 2개 이상의 수치로 표현한 것```

In [12]:
vector1 = torch.tensor([1.,2.,3.])
print(vector1)
# tensor([1.,2.,3.])

vector2 = torch.tensor([4.,5.,6.])
print(vector2)
# tensor([4.,5.,6.])

tensor([1., 2., 3.])
tensor([4., 5., 6.])


- Vector 사칙연산
    - *곱셈과 나눗셈은 각 요소별(element-wise)로 연산*

    - 덧셈

In [15]:
add_vector = vector1 + vector2
print(add_vector)
# tensor([5.,7.,9.])

tensor([5., 7., 9.])


    - 뺄셈

In [16]:
sub_vector = vector1 - vector2
print(sub_vector)
# tensor([-3.,-3.,-3.])

tensor([-3., -3., -3.])


    - 곱셈

In [19]:
mul_vector = vector1 * vector2
print(mul_vector)
# tensor([4., 10., 18.])

tensor([ 4., 10., 18.])


    - 나눗셈

In [20]:
div_vector = vector1 / vector2
print(div_vector)
# tensor([0.2500.,0.4000.,0.5000.])

tensor([0.2500, 0.4000, 0.5000])


- torch 모듈에 내장된 메서드로 vector 사칙연산

In [22]:
torch.add(vector1, vector2)
# tensor([5.,7.,9.,])

tensor([5., 7., 9.])

In [23]:
torch.sub(vector1, vector2)
# tensor([-3.,-3.,-3.])

tensor([-3., -3., -3.])

In [24]:
torch.mul(vector1, vector2)
# tensor([4.,10.,18])

tensor([ 4., 10., 18.])

In [25]:
torch.div(vector1, vector2)
# tensor([0.2500,0.4000,0.5000])

tensor([0.2500, 0.4000, 0.5000])

    - 벡터 값 간 내적
        - 곱 연산이 가능하도록 1*3을 3*1로 바꾸어서 (1*3) * (3*1) 행렬을 계산한 것으로 보임 

In [27]:
torch.dot(vector1, vector2)
# tensor([32.])

tensor(32.)

# Matrix
- ```Matrix``` : ```2개 이상의 벡터 값을 통합해 구성된 값```
- ```벡터 값 간 연산 속도를 빠르게 진행할 수 있는 선형대수의 기본 단위```

In [30]:
matrix1 = torch.tensor([[1.,2.],[3.,4.]])
print(matrix1)
# tensor([[1.,2.],[3.,4.]])

tensor([[1., 2.],
        [3., 4.]])


In [31]:
matrix2 = torch.tensor([[5.,6.],[7.,8.]])
print(matrix2)
# tensor([[5.,6.],[7.,8.]])

tensor([[5., 6.],
        [7., 8.]])


- Matrix 사칙연산

In [32]:
sum_matrix = matrix1 + matrix2
print(sum_matrix)
# tensor([[6.,8.],[10.,12.]])

tensor([[ 6.,  8.],
        [10., 12.]])


In [33]:
sub_matrix = matrix1 - matrix2
print(sub_matrix)
# tensor([[-4.,-4.],[-4.,-4.]])

tensor([[-4., -4.],
        [-4., -4.]])


In [34]:
mul_matrix = matrix1 * matrix2
print(mul_matrix)
# tensor([[5.,12.],[21.,32.]])

tensor([[ 5., 12.],
        [21., 32.]])


In [36]:
div_matrix = matrix1 / matrix2
print(div_matrix)
# tensor([[0.2000,0.3333],[0.4286,0.5000]])

tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])


- torch 모듈에 내장된 메서드로 matrix 사칙 연산 

In [38]:
matrix1, matrix2

(tensor([[1., 2.],
         [3., 4.]]),
 tensor([[5., 6.],
         [7., 8.]]))

In [39]:
torch.add(matrix1, matrix2)
# tensor([6.,8.],[10.,12.])

tensor([[ 6.,  8.],
        [10., 12.]])

In [40]:
torch.sub(matrix1, matrix2)
# tensor([-4.,-4.],[-4.,-4])

tensor([[-4., -4.],
        [-4., -4.]])

In [41]:
torch.mul(matrix1, matrix2)
# tensor([5.,12.],[21.,32.])

tensor([[ 5., 12.],
        [21., 32.]])

In [42]:
torch.div(matrix1, matrix2)
# tensor([0.2000,0.3333],[0.4286,0.5000])

tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])

In [45]:
torch.matmul(matrix1, matrix2)
# tensor([[19,22],[43,50]])

tensor([[19., 22.],
        [43., 50.]])

# Tensor
- ```Tensor``` : ```2차원 이상의 배열```

In [47]:
tensor1 = torch.tensor([[[1.,2.],[3.,4.]],[[5.,6.],[7.,8.]]])
print(tensor1)
# tensor([[[1.,2.],[3.,4.]],[[5.,6],[7.,8.]]])

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [49]:
tensor2 = torch.tensor([[[9.,10.],[11.,12.]],[[13.,14.],[15.,16.]]])
print(tensor2)
# tensor([[[9.,10.],[11.,12.]],[[13.,14.],[15.,16.]]])

tensor([[[ 9., 10.],
         [11., 12.]],

        [[13., 14.],
         [15., 16.]]])


- Tensor 사칙연산

    - 덧셈

In [50]:
sum_tensor = tensor1 + tensor2
print(sum_tensor)
# tensor([[[10.,12.],[14.,16.]],[[18.,20.],[22.,24.]]])

tensor([[[10., 12.],
         [14., 16.]],

        [[18., 20.],
         [22., 24.]]])


    - 뺄셈

In [51]:
sub_tensor = tensor1 - tensor2
print(sub_tensor)
# tensor([[[-8.,-8.],[-8.,-8.]],[[-8.,-8.],[-8.,-8]]])

tensor([[[-8., -8.],
         [-8., -8.]],

        [[-8., -8.],
         [-8., -8.]]])


    - 곱셈

In [52]:
tensor1, tensor2

(tensor([[[1., 2.],
          [3., 4.]],
 
         [[5., 6.],
          [7., 8.]]]),
 tensor([[[ 9., 10.],
          [11., 12.]],
 
         [[13., 14.],
          [15., 16.]]]))

In [53]:
mul_tensor = tensor1 * tensor2
print(mul_tensor)
# tensor([[[9.,20.],[33.,48.]],[[65.,84.],[105.,128.]]])

tensor([[[  9.,  20.],
         [ 33.,  48.]],

        [[ 65.,  84.],
         [105., 128.]]])


    - 나눗셈

In [55]:
div_tensor = tensor1 / tensor2
print(div_tensor)
# tensor([[[0.1111,0.2000],[0.2727,0.3333]],[[0.3846,0.4286],[0.4667,0.5000]]])

tensor([[[0.1111, 0.2000],
         [0.2727, 0.3333]],

        [[0.3846, 0.4286],
         [0.4667, 0.5000]]])


- torch 모듈에 내장된 메서드로 Tensor 사칙 연산 

In [58]:
tensor1, tensor2

(tensor([[[1., 2.],
          [3., 4.]],
 
         [[5., 6.],
          [7., 8.]]]),
 tensor([[[ 9., 10.],
          [11., 12.]],
 
         [[13., 14.],
          [15., 16.]]]))

In [59]:
torch.add(tensor1, tensor2)
# tensor([[[10.,12.],[14.,16.]],[[18.,20.],[22.,24.]]])

tensor([[[10., 12.],
         [14., 16.]],

        [[18., 20.],
         [22., 24.]]])

In [60]:
torch.sub(tensor1, tensor2)
# tensor([[[-8.,-8],[-8.,-8]],[[-8.,-8],[-8.,-8]]])

tensor([[[-8., -8.],
         [-8., -8.]],

        [[-8., -8.],
         [-8., -8.]]])

In [61]:
torch.mul(tensor1, tensor2)
# tensor([[[9.,20.],[33.,48.]],[[65.,84.],[105.,128.]]])

tensor([[[  9.,  20.],
         [ 33.,  48.]],

        [[ 65.,  84.],
         [105., 128.]]])

In [62]:
torch.div(tensor1, tensor2)
# tensor([[[0.1111,0.2000],[0.2727,0.3333]],[[0.3846,0.4286],[0.4667,0.5000]]])

tensor([[[0.1111, 0.2000],
         [0.2727, 0.3333]],

        [[0.3846, 0.4286],
         [0.4667, 0.5000]]])

In [88]:
torch.matmul(tensor1, tensor2)
# tensor([[[31.,34.],[71.,78.]],[[155.,166.],[211.,226.]]])

tensor([[[ 31.,  34.],
         [ 71.,  78.]],

        [[155., 166.],
         [211., 226.]]])

# Tensor 내적 이미지 
<img src='./Tensor 내적.PNG'>